spring:
  config:
    import: optional:file:.env[.properties]

  application:
    name: pos-system

  datasource:
    url: ${DB_URL:jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: ${MAIL_SMTP_AUTH}
          starttls:
            enable: ${MAIL_SMTP_STARTTLS}

  devtools:
    livereload:
      enabled: true

server:
  port: 5000

razorpay:
  api:
    key: ${RAZORPAY_API_KEY:}
    secret: ${RAZORPAY_API_SECRET:}



stripe:
  api:
    key: ${STRIPE_API_KEY:}

gemini:
  api:
    key: ${GEMINI_API_KEY:}

app:
  brand-name: ${APP_BRAND_NAME:SmartPos}
  mail:
    from-name: ${MAIL_FROM_NAME:SmartPos}
  frontend:
    reset-url: http://localhost:5173/auth/reset-password?token=

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql: TRACE
